spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VargasRaymondJ/BootConfigs.git
server:
  port: 8888
eureka:
  instance:
    hostname: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:3671/eureka/